SELECT P.PRODUCT_ID, P.PRODUCT_NAME, P.PRICE * O.SUM_AMOUNT AS TOTAL_SALES
FROM FOOD_PRODUCT P JOIN (
    SELECT PRODUCT_ID, SUM(AMOUNT) AS SUM_AMOUNT
    FROM FOOD_ORDER
    WHERE DATE_FORMAT(PRODUCE_DATE, "%Y-%m") = "2022-05"
    GROUP BY PRODUCT_ID

) AS O
ON P.PRODUCT_ID = O.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID;
