SELECT A.CATEGORY, A.PRICE AS MAX_PRICE, A.PRODUCT_NAME
FROM FOOD_PRODUCT AS A INNER JOIN (
    SELECT CATEGORY, MAX(PRICE) AS MP
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
) AS B
ON A.PRICE = B.MP AND A.CATEGORY = B.CATEGORY
WHERE A.CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY MAX_PRICE DESC;
